### ISSUE TITLE
ssdb-server and ssdb.conf

### ISSUE THREAD

**Issue by hwongcom** [ideawu/ssdb-rocks#4]
for rocksdb, ssdb-server and ssdb.conf is all you need + the directory folder of the data right?

by the way, the configuration for ssdbROCKSDB is under "leveldb"?

same configuration settings?

leveldb:
        # in MB
        cache_size: 500
        # in KB
        block_size: 32
        # in MB
        write_buffer_size: 64
        # in MB
        compaction_speed: 1000
        # yes|no
        compression: no

**Comment by ideawu** [comment]
YES
